CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  display_name text NOT NULL,
  role text NOT NULL CHECK (role IN ('admin', 'member', 'viewer')) DEFAULT 'member',
  is_active boolean NOT NULL DEFAULT true,
  login_count integer NOT NULL DEFAULT 0,
  activity_count integer NOT NULL DEFAULT 0,
  last_login_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auth_sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  refresh_token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_id ON auth_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_token_hash ON auth_sessions(refresh_token_hash);

CREATE TABLE IF NOT EXISTS invites (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  token_hash text NOT NULL UNIQUE,
  role text NOT NULL CHECK (role IN ('admin', 'member', 'viewer')) DEFAULT 'member',
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_invites_token_hash ON invites(token_hash);
CREATE INDEX IF NOT EXISTS idx_invites_email ON invites(lower(email));

CREATE TABLE IF NOT EXISTS user_activity_daily (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  activity_date date NOT NULL,
  activity_count integer NOT NULL DEFAULT 0,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, activity_date)
);

CREATE TABLE IF NOT EXISTS tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  priority text NOT NULL DEFAULT 'Средний',
  column_name text NOT NULL DEFAULT 'Беклог'
    CHECK (column_name IN ('Беклог', 'В работе', 'Готов', 'Архив')),
  due date,
  completed_at timestamptz,
  owner_id integer REFERENCES users(id) ON DELETE SET NULL,
  assignee_id integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tasks_owner_id ON tasks(owner_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee_id ON tasks(assignee_id);

CREATE TABLE IF NOT EXISTS events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  month integer NOT NULL,
  day integer,
  type text NOT NULL DEFAULT '',
  done boolean NOT NULL DEFAULT false,
  owner_id integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_events_owner_id ON events(owner_id);

CREATE TABLE IF NOT EXISTS event_tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id integer NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  done boolean NOT NULL DEFAULT false,
  owner_id integer REFERENCES users(id) ON DELETE SET NULL,
  assignee_id integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_event_tasks_event_id ON event_tasks(event_id);
CREATE INDEX IF NOT EXISTS idx_event_tasks_owner_id ON event_tasks(owner_id);
CREATE INDEX IF NOT EXISTS idx_event_tasks_assignee_id ON event_tasks(assignee_id);

CREATE TABLE IF NOT EXISTS event_members (
  event_id integer NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (event_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_event_members_user_id ON event_members(user_id);

CREATE TABLE IF NOT EXISTS sync_stickers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  speaker text NOT NULL DEFAULT '',
  topic text NOT NULL DEFAULT '',
  text text NOT NULL DEFAULT '',
  color_id text NOT NULL DEFAULT 'sky',
  x numeric NOT NULL DEFAULT 0,
  y numeric NOT NULL DEFAULT 0,
  width numeric NOT NULL DEFAULT 200,
  height numeric NOT NULL DEFAULT 150,
  owner_id integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sync_stickers_owner_id ON sync_stickers(owner_id);

CREATE TABLE IF NOT EXISTS ucp_tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  done boolean NOT NULL DEFAULT false,
  owner_id integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ucp_tasks_owner_id ON ucp_tasks(owner_id);

CREATE TABLE IF NOT EXISTS ucp_checkpoints (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id integer NOT NULL REFERENCES ucp_tasks(id) ON DELETE CASCADE,
  label text NOT NULL DEFAULT '',
  date date,
  done boolean NOT NULL DEFAULT false,
  evidence_materials text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS ucp_task_members (
  task_id integer NOT NULL REFERENCES ucp_tasks(id) ON DELETE CASCADE,
  member_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (task_id, member_id)
);

CREATE TABLE IF NOT EXISTS development_tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  result_image text NOT NULL DEFAULT '',
  success_metric text NOT NULL DEFAULT '',
  due date,
  status text NOT NULL DEFAULT '',
  done boolean NOT NULL DEFAULT false,
  owner_id integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_development_tasks_owner_id ON development_tasks(owner_id);

CREATE TABLE IF NOT EXISTS development_task_checkpoints (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id integer NOT NULL REFERENCES development_tasks(id) ON DELETE CASCADE,
  label text NOT NULL DEFAULT '',
  date date,
  done boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS development_task_members (
  task_id integer NOT NULL REFERENCES development_tasks(id) ON DELETE CASCADE,
  member_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (task_id, member_id)
);

CREATE TABLE IF NOT EXISTS ambp_topics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  plan_revenue numeric(14, 2) NOT NULL DEFAULT 0,
  fact_revenue numeric(14, 2) NOT NULL DEFAULT 0,
  funnel_leads integer NOT NULL DEFAULT 0,
  funnel_qualified integer NOT NULL DEFAULT 0,
  funnel_proposals integer NOT NULL DEFAULT 0,
  funnel_contracts integer NOT NULL DEFAULT 0,
  comment text NOT NULL DEFAULT '',
  owner_id integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES users(id) ON DELETE CASCADE,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_id ON push_subscriptions(user_id);
