import logging
from contextlib import contextmanager
from typing import Any

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from .config import (
    ADMIN_EMAIL, ADMIN_NAME, ADMIN_PASSWORD, DATABASE_URL,
)

logger = logging.getLogger(__name__)

_pool: ConnectionPool | None = None


def init_pool() -> None:
    global _pool
    _pool = ConnectionPool(DATABASE_URL, min_size=2, max_size=10, open=True)


def close_pool() -> None:
    if _pool:
        _pool.close()


@contextmanager
def db():
    if _pool is not None:
        with _pool.connection() as conn:
            conn.row_factory = dict_row
            yield conn
    else:
        with psycopg.connect(DATABASE_URL, row_factory=dict_row) as conn:
            with conn.transaction():
                yield conn


def migrate_auth_schema() -> None:
    from .auth import hash_password
    with db() as conn:
        # Migration versioning table
        conn.execute("""
            CREATE TABLE IF NOT EXISTS schema_migrations (
                version text PRIMARY KEY,
                applied_at timestamptz DEFAULT now()
            )
        """)

        def applied(version: str) -> bool:
            return conn.execute(
                "SELECT 1 FROM schema_migrations WHERE version = %s", (version,)
            ).fetchone() is not None

        def mark_applied(version: str) -> None:
            conn.execute(
                "INSERT INTO schema_migrations (version) VALUES (%s) ON CONFLICT DO NOTHING",
                (version,),
            )

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              email text NOT NULL UNIQUE,
              password_hash text NOT NULL,
              display_name text NOT NULL,
              role text NOT NULL CHECK (role IN ('admin', 'member', 'viewer')) DEFAULT 'member',
              is_active boolean NOT NULL DEFAULT true,
              login_count integer NOT NULL DEFAULT 0,
              activity_count integer NOT NULL DEFAULT 0,
              last_login_at timestamptz,
              last_seen_at timestamptz,
              created_at timestamptz NOT NULL DEFAULT now(),
              updated_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS auth_sessions (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              refresh_token_hash text NOT NULL UNIQUE,
              expires_at timestamptz NOT NULL,
              created_at timestamptz NOT NULL DEFAULT now(),
              revoked_at timestamptz
            )
            """
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_id ON auth_sessions(user_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_auth_sessions_token_hash ON auth_sessions(refresh_token_hash)")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS invites (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              email text NOT NULL,
              token_hash text NOT NULL UNIQUE,
              role text NOT NULL CHECK (role IN ('admin', 'member', 'viewer')) DEFAULT 'member',
              created_by integer REFERENCES users(id) ON DELETE SET NULL,
              expires_at timestamptz NOT NULL,
              used_at timestamptz,
              created_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_invites_token_hash ON invites(token_hash)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_invites_email ON invites(lower(email))")
        conn.execute("ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS login_count integer NOT NULL DEFAULT 0")
        conn.execute("ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS last_seen_at timestamptz")
        conn.execute("ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS activity_count integer NOT NULL DEFAULT 0")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS user_activity_daily (
              user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              activity_date date NOT NULL,
              activity_count integer NOT NULL DEFAULT 0,
              last_seen_at timestamptz NOT NULL DEFAULT now(),
              PRIMARY KEY (user_id, activity_date)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS tasks (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              title text NOT NULL,
              description text NOT NULL DEFAULT '',
              priority text NOT NULL DEFAULT 'Средний',
              column_name text NOT NULL DEFAULT 'Беклог',
              due date,
              completed_at timestamptz,
              creator_id integer REFERENCES users(id) ON DELETE SET NULL,
              owner_id integer REFERENCES users(id) ON DELETE SET NULL,
              assignee_id integer REFERENCES users(id) ON DELETE SET NULL,
              created_at timestamptz NOT NULL DEFAULT now(),
              updated_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS events (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              title text NOT NULL,
              description text NOT NULL DEFAULT '',
              month integer NOT NULL,
              day integer,
              type text NOT NULL DEFAULT '',
              done boolean NOT NULL DEFAULT false,
              owner_id integer REFERENCES users(id) ON DELETE SET NULL,
              created_at timestamptz NOT NULL DEFAULT now(),
              updated_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS task_members (
              task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
              member_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              PRIMARY KEY (task_id, member_id)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS event_tasks (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              event_id integer NOT NULL REFERENCES events(id) ON DELETE CASCADE,
              title text NOT NULL,
              description text NOT NULL DEFAULT '',
              done boolean NOT NULL DEFAULT false,
              owner_id integer REFERENCES users(id) ON DELETE SET NULL,
              assignee_id integer REFERENCES users(id) ON DELETE SET NULL,
              created_at timestamptz NOT NULL DEFAULT now(),
              updated_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS event_members (
              event_id integer NOT NULL REFERENCES events(id) ON DELETE CASCADE,
              user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              PRIMARY KEY (event_id, user_id)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS sync_stickers (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              speaker text NOT NULL DEFAULT '',
              topic text NOT NULL DEFAULT '',
              text text NOT NULL DEFAULT '',
              color_id integer NOT NULL DEFAULT 0,
              x numeric NOT NULL DEFAULT 0,
              y numeric NOT NULL DEFAULT 0,
              width numeric NOT NULL DEFAULT 200,
              height numeric NOT NULL DEFAULT 150,
              owner_id integer REFERENCES users(id) ON DELETE SET NULL,
              created_at timestamptz NOT NULL DEFAULT now(),
              updated_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ucp_tasks (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              title text NOT NULL,
              description text NOT NULL DEFAULT '',
              done boolean NOT NULL DEFAULT false,
              owner_id integer REFERENCES users(id) ON DELETE SET NULL,
              created_at timestamptz NOT NULL DEFAULT now(),
              updated_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ucp_checkpoints (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              task_id integer NOT NULL REFERENCES ucp_tasks(id) ON DELETE CASCADE,
              label text NOT NULL DEFAULT '',
              date date,
              done boolean NOT NULL DEFAULT false,
              evidence_materials text NOT NULL DEFAULT ''
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ucp_task_members (
              task_id integer NOT NULL REFERENCES ucp_tasks(id) ON DELETE CASCADE,
              member_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              PRIMARY KEY (task_id, member_id)
            )
            """
        )
        owner_scoped_tables = ("tasks", "event_tasks", "events", "sync_stickers", "ucp_tasks", "development_tasks", "ambp_topics")
        for table_name in owner_scoped_tables:
            conn.execute(f"ALTER TABLE IF EXISTS {table_name} ADD COLUMN IF NOT EXISTS owner_id integer REFERENCES users(id) ON DELETE SET NULL")
        conn.execute("ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS creator_id integer REFERENCES users(id) ON DELETE SET NULL")
        if not applied("001_backfill_creator_id"):
            conn.execute("UPDATE tasks SET creator_id = owner_id WHERE creator_id IS NULL")
            mark_applied("001_backfill_creator_id")
        conn.execute("ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS assignee_id integer")
        conn.execute("ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS completed_at timestamptz")
        if not applied("002_backfill_completed_at"):
            conn.execute("UPDATE tasks SET completed_at = COALESCE(completed_at, updated_at, now()) WHERE column_name IN ('Готов', 'Готово')")
            mark_applied("002_backfill_completed_at")
        conn.execute("ALTER TABLE IF EXISTS tasks DROP CONSTRAINT IF EXISTS tasks_assignee_id_fkey")
        if not applied("003_nullify_orphan_task_assignees"):
            conn.execute("UPDATE tasks SET assignee_id = NULL WHERE assignee_id IS NOT NULL AND assignee_id NOT IN (SELECT id FROM users)")
            mark_applied("003_nullify_orphan_task_assignees")
        conn.execute("ALTER TABLE IF EXISTS tasks ADD CONSTRAINT tasks_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE SET NULL")
        conn.execute("ALTER TABLE IF EXISTS task_members ADD COLUMN IF NOT EXISTS member_id integer")
        conn.execute("ALTER TABLE IF EXISTS task_members DROP CONSTRAINT IF EXISTS task_members_member_id_fkey")
        if not applied("004_delete_orphan_task_members"):
            conn.execute("DELETE FROM task_members WHERE member_id IS NOT NULL AND member_id NOT IN (SELECT id FROM users)")
            mark_applied("004_delete_orphan_task_members")
        conn.execute("ALTER TABLE IF EXISTS task_members ADD CONSTRAINT task_members_member_id_fkey FOREIGN KEY (member_id) REFERENCES users(id) ON DELETE CASCADE")
        conn.execute("ALTER TABLE IF EXISTS tasks DROP CONSTRAINT IF EXISTS tasks_column_name_check")
        conn.execute("ALTER TABLE IF EXISTS tasks ADD CONSTRAINT tasks_column_name_check CHECK (column_name IN ('Беклог', 'В работе', 'Готов', 'Готово', 'Архив'))")
        if not applied("005_rename_column_gotovo_to_gotov"):
            conn.execute("UPDATE tasks SET column_name = 'Готов' WHERE column_name = 'Готово'")
            mark_applied("005_rename_column_gotovo_to_gotov")
        if not applied("006_archive_old_done_tasks"):
            conn.execute("UPDATE tasks SET column_name = 'Архив' WHERE column_name = 'Готов' AND completed_at <= now() - interval '7 days'")
            mark_applied("006_archive_old_done_tasks")
        conn.execute("ALTER TABLE IF EXISTS event_tasks ADD COLUMN IF NOT EXISTS assignee_id integer")
        conn.execute("ALTER TABLE IF EXISTS event_tasks DROP CONSTRAINT IF EXISTS event_tasks_assignee_id_fkey")
        if not applied("007_nullify_orphan_event_task_assignees"):
            conn.execute("UPDATE event_tasks SET assignee_id = NULL WHERE assignee_id IS NOT NULL AND assignee_id NOT IN (SELECT id FROM users)")
            mark_applied("007_nullify_orphan_event_task_assignees")
        conn.execute("ALTER TABLE IF EXISTS event_tasks ADD CONSTRAINT event_tasks_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE SET NULL")
        conn.execute("ALTER TABLE IF EXISTS ucp_task_members ADD COLUMN IF NOT EXISTS member_id integer")
        conn.execute("ALTER TABLE IF EXISTS ucp_task_members DROP CONSTRAINT IF EXISTS ucp_task_members_member_id_fkey")
        if not applied("008_delete_orphan_ucp_task_members"):
            conn.execute("DELETE FROM ucp_task_members WHERE member_id IS NOT NULL AND member_id NOT IN (SELECT id FROM users)")
            mark_applied("008_delete_orphan_ucp_task_members")
        conn.execute("ALTER TABLE IF EXISTS ucp_task_members ADD CONSTRAINT ucp_task_members_member_id_fkey FOREIGN KEY (member_id) REFERENCES users(id) ON DELETE CASCADE")
        conn.execute("ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS description text")
        conn.execute("ALTER TABLE IF EXISTS event_tasks ADD COLUMN IF NOT EXISTS description text")
        conn.execute("ALTER TABLE IF EXISTS ucp_tasks ADD COLUMN IF NOT EXISTS done boolean NOT NULL DEFAULT false")
        conn.execute("ALTER TABLE IF EXISTS ucp_checkpoints ADD COLUMN IF NOT EXISTS evidence_materials text NOT NULL DEFAULT ''")
        conn.execute("ALTER TABLE IF EXISTS ucp_checkpoints ADD COLUMN IF NOT EXISTS done boolean NOT NULL DEFAULT false")
        conn.execute("ALTER TABLE IF EXISTS development_tasks ADD COLUMN IF NOT EXISTS done boolean NOT NULL DEFAULT false")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS development_tasks (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              title text NOT NULL,
              description text NOT NULL DEFAULT '',
              result_image text NOT NULL DEFAULT '',
              success_metric text NOT NULL DEFAULT '',
              due date,
              status text NOT NULL DEFAULT '',
              done boolean NOT NULL DEFAULT false,
              owner_id integer REFERENCES users(id) ON DELETE SET NULL,
              created_at timestamptz NOT NULL DEFAULT now(),
              updated_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS development_task_checkpoints (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              task_id integer NOT NULL REFERENCES development_tasks(id) ON DELETE CASCADE,
              label text NOT NULL DEFAULT '',
              date date,
              done boolean NOT NULL DEFAULT false
            )
            """
        )
        conn.execute("ALTER TABLE IF EXISTS development_task_checkpoints ADD COLUMN IF NOT EXISTS done boolean NOT NULL DEFAULT false")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS development_task_members (
              task_id integer NOT NULL REFERENCES development_tasks(id) ON DELETE CASCADE,
              member_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              PRIMARY KEY (task_id, member_id)
            )
            """
        )
        conn.execute("ALTER TABLE IF EXISTS development_task_members ADD COLUMN IF NOT EXISTS member_id integer")
        conn.execute("ALTER TABLE IF EXISTS development_task_members DROP CONSTRAINT IF EXISTS development_task_members_member_id_fkey")
        if not applied("009_delete_orphan_dev_task_members"):
            conn.execute("DELETE FROM development_task_members WHERE member_id IS NOT NULL AND member_id NOT IN (SELECT id FROM users)")
            mark_applied("009_delete_orphan_dev_task_members")
        conn.execute("ALTER TABLE IF EXISTS development_task_members ADD CONSTRAINT development_task_members_member_id_fkey FOREIGN KEY (member_id) REFERENCES users(id) ON DELETE CASCADE")
        if not conn.execute("SELECT id FROM development_tasks LIMIT 1").fetchone():
            conn.execute(
                """
                INSERT INTO development_tasks (title, description, result_image, success_metric, due, status)
                VALUES
                  (%s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s)
                """,
                (
                    "Сформировать единую рабочую доску для команды",
                    "Собрать ключевые процессы руководителя в одном dashboard и убрать ручное ведение разрозненных списков.",
                    "Команда видит задачи, события, УПЦ и план развития в едином интерфейсе.",
                    "Не менее 80% рабочих задач ведутся в dashboard.",
                    "2026-06-15",
                    "В работе: базовый backend и авторизация уже готовы.",
                    "Подготовить мобильный клиент",
                    "Сделать iOS-приложение для просмотра и обновления ключевых данных dashboard.",
                    "На iPhone доступен вход, обзор, задачи, события и УПЦ.",
                    "Приложение проходит smoke-test входа и загрузки данных.",
                    "2026-07-01",
                    "Начат SwiftUI-каркас.",
                    "Настроить командную работу",
                    "Добавить коллег через invite-ссылки и договориться о правилах заполнения разделов.",
                    "Каждый участник имеет доступ и понимает, где фиксировать свои изменения.",
                    "Все приглашённые пользователи вошли и обновили хотя бы одну задачу.",
                    "2026-07-15",
                    "Планируется.",
                ),
            )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ambp_topics (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              title text NOT NULL,
              description text NOT NULL DEFAULT '',
              plan_revenue numeric(14, 2) NOT NULL DEFAULT 0,
              fact_revenue numeric(14, 2) NOT NULL DEFAULT 0,
              funnel_leads integer NOT NULL DEFAULT 0,
              funnel_qualified integer NOT NULL DEFAULT 0,
              funnel_proposals integer NOT NULL DEFAULT 0,
              funnel_contracts integer NOT NULL DEFAULT 0,
              comment text NOT NULL DEFAULT '',
              owner_id integer REFERENCES users(id) ON DELETE SET NULL,
              created_at timestamptz NOT NULL DEFAULT now(),
              updated_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        if not conn.execute("SELECT id FROM ambp_topics LIMIT 1").fetchone():
            conn.execute(
                """
                INSERT INTO ambp_topics (
                  title, description, plan_revenue, fact_revenue,
                  funnel_leads, funnel_qualified, funnel_proposals, funnel_contracts, comment
                )
                VALUES
                  (%s, %s, %s, %s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    "Импортозамещение ЕСФМ", "Крупнейший резерв дополнительной выручки по бизнес-плану.", 45.0, 1.2, 18, 11, 5, 1, "Требуется усилить роли и владельцев активностей для ускорения результата.",
                    "Проект Рейс контроль", "Проектная тема с подтверждённой ответственностью и активной командой.", 35.67, 9.0, 22, 15, 8, 3, "Работы ведутся, команда собрана, активность уже конвертируется в факт.",
                    "Ресурс для ЕМЦ", "Потенциал дополнительной выручки через работу с ресурсной базой.", 17.49, 1.27, 12, 7, 3, 1, "Нужна детализация ближайших действий и подтверждение клиентского контура.",
                    "Ресурс для ДЦО", "Отдельный резерв по дополнительной выручке бизнес-плана.", 17.12, 2.57, 10, 6, 4, 2, "Есть первичный факт, требуется довести активности до устойчивого темпа.",
                ),
            )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS push_subscriptions (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_id integer REFERENCES users(id) ON DELETE CASCADE,
              endpoint text NOT NULL UNIQUE,
              p256dh text NOT NULL,
              auth text NOT NULL,
              user_agent text NOT NULL DEFAULT '',
              created_at timestamptz NOT NULL DEFAULT now(),
              updated_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_id ON push_subscriptions(user_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_tasks_owner_id ON tasks(owner_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_tasks_assignee_id ON tasks(assignee_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_events_owner_id ON events(owner_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_event_tasks_event_id ON event_tasks(event_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_event_tasks_owner_id ON event_tasks(owner_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_event_tasks_assignee_id ON event_tasks(assignee_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_event_members_user_id ON event_members(user_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_sync_stickers_owner_id ON sync_stickers(owner_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_ucp_tasks_owner_id ON ucp_tasks(owner_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_development_tasks_owner_id ON development_tasks(owner_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_ucp_checkpoints_task_id ON ucp_checkpoints (task_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_dev_checkpoints_task_id ON development_task_checkpoints (task_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_task_members_task_id ON task_members (task_id)")
        admin_owner = conn.execute("SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1").fetchone()
        if not admin_owner:
            admin_owner = conn.execute("SELECT id FROM users ORDER BY id LIMIT 1").fetchone()
        if not applied("010_backfill_owner_id_pre_admin"):
            if admin_owner:
                for table_name in owner_scoped_tables:
                    conn.execute(f"UPDATE {table_name} SET owner_id = %s WHERE owner_id IS NULL", (admin_owner["id"],))
            mark_applied("010_backfill_owner_id_pre_admin")
        if ADMIN_EMAIL and ADMIN_PASSWORD:
            existing = conn.execute("SELECT id FROM users WHERE lower(email) = lower(%s)", (ADMIN_EMAIL,)).fetchone()
            if not existing:
                conn.execute(
                    "INSERT INTO users (email, password_hash, display_name, role) VALUES (%s, %s, %s, 'admin')",
                    (ADMIN_EMAIL.lower(), hash_password(ADMIN_PASSWORD), ADMIN_NAME),
                )
        if not applied("011_backfill_owner_id_post_admin"):
            admin_owner = conn.execute("SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1").fetchone()
            if admin_owner:
                for table_name in owner_scoped_tables:
                    conn.execute(f"UPDATE {table_name} SET owner_id = %s WHERE owner_id IS NULL", (admin_owner["id"],))
            mark_applied("011_backfill_owner_id_post_admin")
